
name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper-compat libgtk-3-dev libnotify-dev pkg-config devscripts

      - name: Build binaries
        run: make

      - name: Get next version
        id: get_next_version
        run: |
          LATEST_TAG=$(git describe --tags --match "v1.0.*" --abbrev=0 2>/dev/null || echo "v1.0.0")
          if [[ "$LATEST_TAG" == "v1.0.0" ]]; then
            NEXT_VERSION="v1.0.0"
          else
            # Extract the patch number and increment it
            PATCH_NUMBER=$(echo "$LATEST_TAG" | sed 's/v1.0.//')
            NEXT_PATCH=$((PATCH_NUMBER + 1))
            NEXT_VERSION="v1.0.${NEXT_PATCH}"
          fi
          NEXT_VERSION_DEB="${NEXT_VERSION#v}"
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_OUTPUT
          echo "NEXT_VERSION_DEB=$NEXT_VERSION_DEB" >> $GITHUB_OUTPUT

      - name: Create upstream tarball
        run: |
          VERSION="${{ steps.get_next_version.outputs.NEXT_VERSION_DEB }}"
          PACKAGE_NAME="pif-gtk"
          TARBALL_NAME="${PACKAGE_NAME}_${VERSION}.orig.tar.gz"
          git archive --format=tar.gz --prefix=${PACKAGE_NAME}-${VERSION}/ HEAD > ../${TARBALL_NAME}

      - name: Build Debian package
        run: |
          export DEBEMAIL="action@github.com"
          export EMAIL="action@github.com"
          dch -v ${{ steps.get_next_version.outputs.NEXT_VERSION_DEB }} "New release"
          dpkg-buildpackage -us -uc

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_next_version.outputs.NEXT_VERSION }}
          release_name: Release ${{ steps.get_next_version.outputs.NEXT_VERSION }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      

      

      - name: Upload pif binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pif
          asset_name: pif
          asset_content_type: application/octet-stream

      - name: Upload pif-gtk binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pif-gtk
          asset_name: pif-gtk
          asset_content_type: application/octet-stream

      - name: Upload Debian package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ../pif-gtk_0.0.${{ github.run_number }}_amd64.deb
          asset_name: pif-gtk_${{ steps.get_next_version.outputs.NEXT_VERSION_DEB }}_amd64.deb
          asset_content_type: application/vnd.debian.binary-package
